#!/usr/bin/env node
// Regenerates dist/ from base/tokens.json. No dependencies (Node >= 18).
//   node build.mjs          write dist/
//   node build.mjs --check  exit 1 if dist/ is out of date (or an export in package.json points nowhere)
//
// Outputs:
//   dist/base/{tokens.css,fonts.css,components.css,tokens.resolved.json}   shared layer, --pyr-* variables
//   dist/fonts.css                                                          legacy alias of the base fonts (paths relative to dist/)
//   dist/landing/*.css, dist/logo/{pyrlyn,listepo}/                         copied byte for byte
//
// The product brand packs (rtok, ketch, cox) are not built here any more: each product repo has a
// brand/ folder that extends @pyrlyn/brand/base/tokens.json and builds its own dist/ (see README).
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, statSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { ranAsScript } from "./scripts/cli.mjs";

const root = dirname(fileURLToPath(import.meta.url));
const readJson = (rel) => JSON.parse(readFileSync(join(root, rel), "utf8"));
const BASE = readJson("base/tokens.json");

// ---------- helpers ----------
export const tokens = (group) =>
  Object.entries(group).filter(([k, v]) => !k.startsWith("$") && v && typeof v === "object" && "$value" in v);
export const hexToRgb = (hex) => {
  const h = hex.replace("#", "");
  return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16));
};
export const rgbChannels = (hex) => hexToRgb(hex).join(" ");
export const bezier = (a) => `cubic-bezier(${a.join(", ")})`;
export const lineHeight = (t) => t.$extensions?.["com.listepo.lineHeight"];
export const family = (arr) => arr.map((f) => (/\s/.test(f) ? `"${f}"` : f)).join(", ");

// ---------- fonts ----------
const fontFiles = { regular: "Regular", semibold: "SemiBold", bold: "Bold" };
const fontFaces = (dir) => Object.entries(fontFiles)
  .map(
    ([w, f]) =>
      `@font-face {\n  font-family: "IBM Plex Mono";\n  font-style: normal;\n  font-weight: ${BASE.font.weight[w].$value};\n  font-display: swap;\n  src: url("${dir}IBMPlexMono-${f}.woff2") format("woff2");\n}`
  )
  .join("\n");

// ---------- base layer (dist/base/, --pyr-*) ----------
const ROLES = BASE.$extensions["com.pyrlyn.roles"];
export const isRole = (k) => ROLES.core.includes(k) || k in ROLES.optional;
const baseStatic = () => {
  const l = [];
  l.push(`  --pyr-font-mono: ${family(BASE.font.family.mono.$value)};`);
  for (const [k, t] of tokens(BASE.font.weight)) l.push(`  --pyr-weight-${k}: ${t.$value};`);
  for (const [k, t] of tokens(BASE.font.size)) { l.push(`  --pyr-text-${k}: ${t.$value};`); l.push(`  --pyr-leading-${k}: ${lineHeight(t)};`); }
  for (const [k, t] of tokens(BASE.font.tracking)) l.push(`  --pyr-tracking-${k}: ${t.$value};`);
  for (const [k, t] of tokens(BASE.space)) l.push(`  --pyr-space-${k}: ${t.$value};`);
  for (const [k, t] of tokens(BASE.radius)) l.push(`  --pyr-radius-${k}: ${t.$value};`);
  for (const [k, t] of tokens(BASE.size)) l.push(`  --pyr-size-${k}: ${t.$value};`);
  for (const [k, t] of tokens(BASE.breakpoint)) l.push(`  --pyr-bp-${k}: ${t.$value}; /* reference only: custom properties do not work in @media */`);
  for (const [k, t] of tokens(BASE.motion.duration)) l.push(`  --pyr-duration-${k}: ${t.$value};`);
  for (const [k, t] of tokens(BASE.motion.easing)) l.push(`  --pyr-ease-${k}: ${bezier(t.$value)};`);
  l.push(`  --pyr-opacity-disabled: ${BASE.opacity.disabled.$value};`);
  l.push(`  --pyr-glass-blur: ${BASE.effect["glass-blur"].$value};`);
  return l.join("\n");
};
const BASE_HEADER = "Generated by build.mjs from base/tokens.json. Do not edit by hand.";
const baseTokensCss = `/* Pyrlyn base tokens: type, space, radii, sizes, motion, opacity, glass blur. ${BASE_HEADER}
 * No colours here: import a product brand instead (each product repo's brand/dist/tokens.css imports this file
 * and sets the semantic colour roles --pyr-bg, --pyr-fg, --pyr-accent …). prefers-reduced-motion collapses every duration. */
:root {
${baseStatic()}
}

@media (prefers-reduced-motion: reduce) {
  :root {
${tokens(BASE.motion.duration).map(([k]) => `    --pyr-duration-${k}: 0.01ms;`).join("\n")}
  }
}
`;
const baseFontsCss = `/* IBM Plex Mono (SIL OFL 1.1, see base/fonts/OFL.txt). ${BASE_HEADER}
 * Paths are relative to dist/base/. Preload the regular weight in <head>:
 * <link rel="preload" href="/path/to/brand/base/fonts/IBMPlexMono-Regular.woff2" as="font" type="font/woff2" crossorigin> */
${fontFaces("../../base/fonts/")}
`;
const legacyFontsCss = `/* IBM Plex Mono (SIL OFL 1.1, see base/fonts/OFL.txt). ${BASE_HEADER}
 * Legacy path (v0.2.0): same faces as dist/base/fonts.css, with paths relative to dist/. Preload the regular weight in <head>:
 * <link rel="preload" href="/path/to/brand/base/fonts/IBMPlexMono-Regular.woff2" as="font" type="font/woff2" crossorigin> */
${fontFaces("../base/fonts/")}
`;
// Optional roles get their documented fallback wherever the components read them.
const componentsSrc = readFileSync(join(root, "base/components/components.css"), "utf8");
export const withFallbacks = (css) =>
  css.replace(/var\(--pyr-([a-z0-9-]+?)(-rgb)?\)/g, (m, role, rgb) => {
    if (!(role in ROLES.optional)) return m;
    const fb = ROLES.optional[role];
    if (!rgb) return `var(--pyr-${role}, ${fb})`;
    const ref = fb.match(/^var\(--pyr-([a-z0-9-]+)\)$/);
    if (ref) return `var(--pyr-${role}-rgb, var(--pyr-${ref[1]}-rgb))`;
    if (/^#[0-9A-Fa-f]{6}$/.test(fb)) return `var(--pyr-${role}-rgb, ${rgbChannels(fb)})`;
    return m;
  });
const baseComponentsCss = `/* Generated by build.mjs from base/components/components.css (+ fallbacks for optional roles from base/tokens.json). Do not edit by hand. */\n` + withFallbacks(componentsSrc);
const baseResolved = {
  $comment: BASE_HEADER,
  roles: { core: ROLES.core, optional: ROLES.optional },
  font: {
    mono: BASE.font.family.mono.$value,
    weight: Object.fromEntries(tokens(BASE.font.weight).map(([k, t]) => [k, t.$value])),
    size: Object.fromEntries(tokens(BASE.font.size).map(([k, t]) => [k, { size: t.$value, lineHeight: lineHeight(t) }])),
  },
  space: Object.fromEntries(tokens(BASE.space).map(([k, t]) => [k, t.$value])),
  radius: Object.fromEntries(tokens(BASE.radius).map(([k, t]) => [k, t.$value])),
  size: Object.fromEntries(tokens(BASE.size).map(([k, t]) => [k, t.$value])),
  breakpoint: Object.fromEntries(tokens(BASE.breakpoint).map(([k, t]) => [k, t.$value])),
};

const out = {
  "dist/base/tokens.css": baseTokensCss,
  "dist/base/fonts.css": baseFontsCss,
  "dist/base/components.css": baseComponentsCss,
  "dist/base/tokens.resolved.json": JSON.stringify(baseResolved, null, 2) + "\n",
  "dist/fonts.css": legacyFontsCss,
};

// ---------- copied as-is: landing theme + logos ----------
// Files only (no recursion), skipping dotfiles; logo/pyrlyn/_build/ (the generator) stays out of dist/.
const files = (dir) =>
  readdirSync(join(root, dir)).filter((f) => !f.startsWith(".") && statSync(join(root, dir, f)).isFile()).sort();
const copies = [
  ["themes/landing", "dist/landing"],
  ["logo/pyrlyn", "dist/logo/pyrlyn"],
  ["logo/listepo", "dist/logo/listepo"],
];
for (const [from, to] of copies) for (const f of files(from)) out[`${to}/${f}`] = readFileSync(join(root, from, f));

if (ranAsScript(import.meta.url)) {
const check = process.argv.includes("--check");
let stale = 0;
const same = (p, content) => existsSync(p) && Buffer.from(readFileSync(p)).equals(Buffer.from(content));
for (const [rel, content] of Object.entries(out)) {
  const p = join(root, rel);
  if (check) {
    if (!same(p, content)) { console.error(`stale: ${rel}`); stale++; }
  } else {
    if (same(p, content)) continue;
    mkdirSync(dirname(p), { recursive: true });
    writeFileSync(p, content);
    console.log(`wrote ${rel}`);
  }
}
// Files in dist/ that the build no longer produces are stale too.
const walk = (d) => readdirSync(join(root, d)).flatMap((f) => (statSync(join(root, d, f)).isDirectory() ? walk(`${d}/${f}`) : [`${d}/${f}`]));
for (const f of existsSync(join(root, "dist")) ? walk("dist") : []) if (!(f in out)) { console.error(`${check ? "stale" : "orphan (delete it)"}: ${f}`); stale++; }
// Every "exports" target must exist (a wildcard target needs its folder).
const pkg = readJson("package.json");
for (const [k, v] of Object.entries(pkg.exports)) {
  const target = (v.endsWith("*") ? dirname(v) : v).replace(/^\.\//, "");
  if (!(existsSync(join(root, target)) || target in out)) { console.error(`export ${k} -> ${v}: missing`); stale++; }
}
for (const [k, v] of Object.entries(pkg.bin ?? {})) if (!existsSync(join(root, v))) { console.error(`bin ${k} -> ${v}: missing`); stale++; }
if (check) { if (stale) { console.error("run: node build.mjs"); process.exit(1); } console.log("dist/ is up to date"); }
else if (stale) process.exit(1);
}
