#!/usr/bin/env node
// Regenerates dist/ from tokens/tokens.json. No dependencies (Node >= 18).
//   node build.mjs          write dist/
//   node build.mjs --check  exit 1 if dist/ is out of date
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = dirname(fileURLToPath(import.meta.url));
const T = JSON.parse(readFileSync(join(root, "tokens/tokens.json"), "utf8"));
const HEADER = "Generated by build.mjs from tokens/tokens.json. Do not edit by hand.";

// ---------- helpers ----------
const get = (path) => path.split(".").reduce((o, k) => o?.[k], T);
const resolve = (v) => {
  if (typeof v === "string") {
    const m = v.match(/^\{([^}]+)\}$/);
    if (m) {
      const t = get(m[1]);
      if (!t || !("$value" in t)) throw new Error(`unresolved reference ${v}`);
      return resolve(t.$value);
    }
  }
  return v;
};
const tokens = (group) =>
  Object.entries(group).filter(([k, v]) => !k.startsWith("$") && v && typeof v === "object" && "$value" in v);
const hexToRgb = (hex) => {
  const h = hex.replace("#", "");
  return [0, 2, 4].map((i) => parseInt(h.slice(i, i + 2), 16));
};
const hasAlpha = (hex) => hex.replace("#", "").length === 8;
const rgbChannels = (hex) => hexToRgb(hex).join(" ");
const bezier = (a) => `cubic-bezier(${a.join(", ")})`;
const remPx = (v) => (v.endsWith("rem") ? `${parseFloat(v) * 16}px` : v);
const lineHeight = (t) => t.$extensions?.["com.listepo.lineHeight"];
const family = (arr) => arr.map((f) => (/\s/.test(f) ? `"${f}"` : f)).join(", ");

const themes = ["dark", "light"];
const themeColors = Object.fromEntries(
  themes.map((th) => [th, Object.fromEntries(tokens(T.theme[th]).map(([k, t]) => [k, resolve(t.$value).toUpperCase()]))])
);
const shadowCss = (name, th) =>
  T.shadow[name].$value
    .map((s) => {
      // A reference to theme.<any>.shine means "this theme's shine".
      const c = /^\{theme\.[a-z]+\.shine\}$/.test(s.color) ? themeColors[th].shine : resolve(s.color);
      return `${s.inset ? "inset " : ""}${s.offsetX} ${s.offsetY} ${s.blur} ${s.spread} rgb(${rgbChannels(c)} / ${s.alpha})`;
    })
    .join(", ");

// ---------- tokens.css ----------
function themeBlock(th, indent = "  ") {
  const c = themeColors[th];
  const lines = [`${indent}color-scheme: ${th};`];
  for (const [k, v] of Object.entries(c)) {
    lines.push(`${indent}--rtok-${k}: ${v};`);
    if (!hasAlpha(v)) lines.push(`${indent}--rtok-${k}-rgb: ${rgbChannels(v)};`);
  }
  lines.push(`${indent}--rtok-glass-alpha: ${T.effect[`glass-alpha-${th}`].$value};`);
  for (const s of tokens(T.shadow)) lines.push(`${indent}--rtok-shadow-${s[0]}: ${shadowCss(s[0], th)};`);
  lines.push(`${indent}--rtok-ring: 0 0 0 2px var(--rtok-bg), 0 0 0 4px var(--rtok-focus);`);
  return lines.join("\n");
}
function staticBlock() {
  const l = [];
  for (const [k, t] of tokens(T.brand)) l.push(`  --rtok-brand-${k}: ${t.$value};`);
  l.push(`  --rtok-font-mono: ${family(T.font.family.mono.$value)};`);
  for (const [k, t] of tokens(T.font.weight)) l.push(`  --rtok-weight-${k}: ${t.$value};`);
  for (const [k, t] of tokens(T.font.size)) {
    l.push(`  --rtok-text-${k}: ${t.$value};`);
    l.push(`  --rtok-leading-${k}: ${lineHeight(t)};`);
  }
  for (const [k, t] of tokens(T.font.tracking)) l.push(`  --rtok-tracking-${k}: ${t.$value};`);
  for (const [k, t] of tokens(T.space)) l.push(`  --rtok-space-${k}: ${t.$value};`);
  for (const [k, t] of tokens(T.radius)) l.push(`  --rtok-radius-${k}: ${t.$value};`);
  for (const [k, t] of tokens(T.size)) l.push(`  --rtok-size-${k}: ${t.$value};`);
  for (const [k, t] of tokens(T.breakpoint)) l.push(`  --rtok-bp-${k}: ${t.$value}; /* reference only: custom properties do not work in @media */`);
  for (const [k, t] of tokens(T.motion.duration)) l.push(`  --rtok-duration-${k}: ${t.$value};`);
  for (const [k, t] of tokens(T.motion.easing)) l.push(`  --rtok-ease-${k}: ${bezier(t.$value)};`);
  l.push(`  --rtok-opacity-disabled: ${T.opacity.disabled.$value};`);
  l.push(`  --rtok-glass-blur: ${T.effect["glass-blur"].$value};`);
  return l.join("\n");
}
const tokensCss = `/* rtok brand tokens. ${HEADER}
 * Dark is the default. Force a theme with <html data-theme="dark|light"> (or class "dark" / "light");
 * without one, prefers-color-scheme picks. prefers-reduced-motion collapses every duration. */
:root {
${staticBlock()}
}

:root,
[data-theme="dark"],
.dark {
${themeBlock("dark")}
}

@media (prefers-color-scheme: light) {
  :root:not([data-theme]):not(.dark) {
${themeBlock("light", "    ")}
  }
}

[data-theme="light"],
.light {
${themeBlock("light")}
}

@media (prefers-reduced-motion: reduce) {
  :root {
${tokens(T.motion.duration).map(([k]) => `    --rtok-duration-${k}: 0.01ms;`).join("\n")}
  }
}
`;

// ---------- fonts.css ----------
const fontFiles = { regular: "Regular", semibold: "SemiBold", bold: "Bold" };
const fontsCss = `/* IBM Plex Mono (SIL OFL 1.1, see fonts/OFL.txt). ${HEADER}
 * Paths are relative to dist/. Preload the regular weight in <head>:
 * <link rel="preload" href="/path/to/brand/fonts/IBMPlexMono-Regular.woff2" as="font" type="font/woff2" crossorigin> */
${Object.entries(fontFiles)
  .map(
    ([w, f]) =>
      `@font-face {\n  font-family: "IBM Plex Mono";\n  font-style: normal;\n  font-weight: ${T.font.weight[w].$value};\n  font-display: swap;\n  src: url("../fonts/IBMPlexMono-${f}.woff2") format("woff2"),\n       url("../fonts/IBMPlexMono-${f}.ttf") format("truetype");\n}`
  )
  .join("\n")}
`;

// ---------- tailwind v3 preset ----------
const semanticNames = Object.keys(themeColors.dark);
const twColor = (k) => (hasAlpha(themeColors.dark[k]) ? `var(--rtok-${k})` : `rgb(var(--rtok-${k}-rgb) / <alpha-value>)`);
const twColors = {
  bg: twColor("bg"),
  surface: { DEFAULT: twColor("surface"), 2: twColor("surface-2"), 3: twColor("surface-3") },
  border: { DEFAULT: twColor("border"), strong: twColor("border-strong") },
  fg: { DEFAULT: twColor("fg"), muted: twColor("fg-muted"), subtle: twColor("fg-subtle") },
  accent: { DEFAULT: twColor("accent"), fg: twColor("accent-fg"), muted: twColor("accent-muted"), on: twColor("on-accent") },
  delta: { DEFAULT: twColor("delta"), fg: twColor("delta-fg") },
  danger: { DEFAULT: twColor("danger"), fg: twColor("danger-fg") },
  success: { DEFAULT: twColor("success"), fg: twColor("success-fg") },
  warn: { DEFAULT: twColor("warn"), fg: twColor("warn-fg") },
  focus: twColor("focus"),
  mark: twColor("mark-tile"),
  brand: Object.fromEntries(tokens(T.brand).map(([k, t]) => [k, t.$value])),
};
const covered = new Set(["bg","surface","surface-2","surface-3","border","border-strong","fg","fg-muted","fg-subtle","accent","accent-fg","accent-muted","on-accent","delta","delta-fg","danger","danger-fg","success","success-fg","warn","warn-fg","focus","mark-tile","shine","selection"]);
for (const k of semanticNames) if (!covered.has(k)) throw new Error(`theme token ${k} not mapped in tailwind preset`);
const preset = {
  darkMode: ["variant", '&:where([data-theme="dark"], [data-theme="dark"] *, .dark, .dark *)'],
  theme: {
    // Full override (not extend) so xs sorts before sm in the generated media queries.
    screens: Object.fromEntries(tokens(T.breakpoint).map(([k, t]) => [k, t.$value])),
    extend: {
      colors: twColors,
      fontFamily: { mono: T.font.family.mono.$value.map((f) => (/\s/.test(f) ? `"${f}"` : f)) },
      fontSize: Object.fromEntries(tokens(T.font.size).map(([k, t]) => [k, [t.$value, { lineHeight: lineHeight(t) }]])),
      fontWeight: Object.fromEntries(tokens(T.font.weight).map(([k, t]) => [k, String(t.$value)])),
      letterSpacing: Object.fromEntries(tokens(T.font.tracking).map(([k, t]) => [k, t.$value])),
      borderRadius: Object.fromEntries(tokens(T.radius).map(([k, t]) => [k, t.$value])),
      boxShadow: { e1: "var(--rtok-shadow-e1)", e2: "var(--rtok-shadow-e2)", e3: "var(--rtok-shadow-e3)", ring: "var(--rtok-ring)" },
      spacing: Object.fromEntries(tokens(T.size).map(([k, t]) => [k, t.$value])),
      transitionDuration: Object.fromEntries(tokens(T.motion.duration).map(([k]) => [k, `var(--rtok-duration-${k})`])),
      transitionTimingFunction: Object.fromEntries(tokens(T.motion.easing).map(([k, t]) => [k, bezier(t.$value)])),
      opacity: { disabled: String(T.opacity.disabled.$value) },
    },
  },
};
const presetJs = `/* rtok brand, Tailwind CSS v3 preset. ${HEADER}
 * Colors read CSS variables from dist/tokens.css, so load that stylesheet too.
 * Usage: module.exports = { presets: [require("@listepo/brand/tailwind-preset")], content: [...] } */
module.exports = ${JSON.stringify(preset, null, 2)};
`;

// ---------- tailwind v4 ----------
const v4 = [];
const v4c = (name, k) => v4.push(`  --color-${name}: var(--rtok-${k});`);
v4c("bg", "bg"); v4c("surface", "surface"); v4c("surface-2", "surface-2"); v4c("surface-3", "surface-3");
v4c("border", "border"); v4c("border-strong", "border-strong");
v4c("fg", "fg"); v4c("fg-muted", "fg-muted"); v4c("fg-subtle", "fg-subtle");
v4c("accent", "accent"); v4c("accent-fg", "accent-fg"); v4c("accent-muted", "accent-muted"); v4c("accent-on", "on-accent");
for (const k of ["delta", "delta-fg", "danger", "danger-fg", "success", "success-fg", "warn", "warn-fg", "focus"]) v4c(k, k);
v4c("mark", "mark-tile");
for (const [k, t] of tokens(T.brand)) v4.push(`  --color-brand-${k}: ${t.$value};`);
v4.push(`  --font-mono: var(--rtok-font-mono);`);
for (const [k, t] of tokens(T.font.size)) {
  v4.push(`  --text-${k}: ${t.$value};`);
  v4.push(`  --text-${k}--line-height: ${lineHeight(t)};`);
}
for (const [k, t] of tokens(T.font.tracking)) v4.push(`  --tracking-${k}: ${t.$value};`);
for (const [k, t] of tokens(T.radius)) v4.push(`  --radius-${k}: ${t.$value};`);
for (const k of ["e1", "e2", "e3"]) v4.push(`  --shadow-${k}: var(--rtok-shadow-${k});`);
v4.push(`  --shadow-ring: var(--rtok-ring);`);
for (const [k, t] of tokens(T.size)) v4.push(`  --spacing-${k}: ${t.$value};`);
for (const [k, t] of tokens(T.breakpoint)) v4.push(`  --breakpoint-${k}: ${t.$value};`);
for (const [k, t] of tokens(T.motion.easing)) v4.push(`  --ease-${k}: ${bezier(t.$value)};`);
const v4Css = `/* rtok brand, Tailwind CSS v4 theme. ${HEADER}
 * Usage (after @import "tailwindcss";):  @import "@listepo/brand/tailwind-v4.css";
 * Utilities: bg-bg bg-surface text-fg text-fg-muted border-border bg-accent text-accent-on
 * text-accent-fg bg-accent/15 rounded-md shadow-e2 shadow-ring font-mono text-sm duration-fast */
@import "./tokens.css";

@custom-variant dark (&:where([data-theme="dark"], [data-theme="dark"] *, .dark, .dark *));

@theme inline {
${v4.join("\n")}
}

@utility duration-fast { transition-duration: var(--rtok-duration-fast); }
@utility duration-base { transition-duration: var(--rtok-duration-base); }
@utility duration-slow { transition-duration: var(--rtok-duration-slow); }
`;

// ---------- slint ----------
const sl = [];
for (const [k] of Object.entries(themeColors.dark)) {
  const d = themeColors.dark[k], l = themeColors.light[k];
  sl.push(`    out property <color> ${k}: ${d === l ? d : `dark ? ${d} : ${l}`};`);
}
const slStatic = [];
for (const [k, t] of tokens(T.brand)) slStatic.push(`    out property <color> brand-${k}: ${t.$value};`);
slStatic.push(`    out property <string> font-family: "${T.font.family.mono.$value[0]}";`);
for (const [k, t] of tokens(T.font.weight)) slStatic.push(`    out property <int> weight-${k}: ${t.$value};`);
for (const [k, t] of tokens(T.font.size)) slStatic.push(`    out property <length> text-${k}: ${remPx(t.$value)};`);
for (const [k, t] of tokens(T.space)) slStatic.push(`    out property <length> space-${k}: ${t.$value};`);
for (const [k, t] of tokens(T.radius)) slStatic.push(`    out property <length> radius-${k}: ${k === "full" ? "9999px" : t.$value};`);
for (const [k, t] of tokens(T.size)) slStatic.push(`    out property <length> size-${k}: ${t.$value};`);
for (const [k, t] of tokens(T.breakpoint)) slStatic.push(`    out property <length> bp-${k}: ${t.$value};`);
for (const [k, t] of tokens(T.motion.duration)) slStatic.push(`    out property <duration> duration-${k}: ${t.$value};`);
slStatic.push(`    out property <float> opacity-disabled: ${T.opacity.disabled.$value};`);
const slint = `// rtok brand tokens for Slint. ${HEADER}
// import { Tokens } from "tokens.slint";   then: background: Tokens.bg;  Tokens.dark = false;
// Slint has no prefers-reduced-motion: set durations to 0ms yourself when the OS asks.
export global Tokens {
    in-out property <bool> dark: true;

${sl.join("\n")}

${slStatic.join("\n")}
}
`;

// ---------- resolved json ----------
const resolved = {
  $comment: HEADER,
  dark: themeColors.dark,
  light: themeColors.light,
  brand: Object.fromEntries(tokens(T.brand).map(([k, t]) => [k, t.$value])),
  font: { mono: T.font.family.mono.$value, weight: Object.fromEntries(tokens(T.font.weight).map(([k, t]) => [k, t.$value])), size: Object.fromEntries(tokens(T.font.size).map(([k, t]) => [k, { size: t.$value, lineHeight: lineHeight(t) }])) },
  space: Object.fromEntries(tokens(T.space).map(([k, t]) => [k, t.$value])),
  radius: Object.fromEntries(tokens(T.radius).map(([k, t]) => [k, t.$value])),
  size: Object.fromEntries(tokens(T.size).map(([k, t]) => [k, t.$value])),
  breakpoint: Object.fromEntries(tokens(T.breakpoint).map(([k, t]) => [k, t.$value])),
  motion: { duration: Object.fromEntries(tokens(T.motion.duration).map(([k, t]) => [k, t.$value])), easing: Object.fromEntries(tokens(T.motion.easing).map(([k, t]) => [k, bezier(t.$value)])) },
  shadow: { dark: Object.fromEntries(tokens(T.shadow).map(([k]) => [k, shadowCss(k, "dark")])), light: Object.fromEntries(tokens(T.shadow).map(([k]) => [k, shadowCss(k, "light")])) },
};

// ---------- components.css (copied, token-only) ----------
const componentsCss = `/* ${HEADER.replace("from tokens/tokens.json", "(copied from components/components.css)")} */\n` + readFileSync(join(root, "components/components.css"), "utf8");

// ---------- write / check ----------
const out = {
  "dist/tokens.css": tokensCss,
  "dist/fonts.css": fontsCss,
  "dist/components.css": componentsCss,
  "dist/tailwind.preset.js": presetJs,
  "dist/tailwind-v4.css": v4Css,
  "dist/tokens.slint": slint,
  "dist/tokens.resolved.json": JSON.stringify(resolved, null, 2) + "\n",
};
const check = process.argv.includes("--check");
let stale = 0;
for (const [rel, content] of Object.entries(out)) {
  const p = join(root, rel);
  if (check) {
    if (!existsSync(p) || readFileSync(p, "utf8") !== content) { console.error(`stale: ${rel}`); stale++; }
  } else {
    mkdirSync(dirname(p), { recursive: true });
    writeFileSync(p, content);
    console.log(`wrote ${rel}`);
  }
}
if (check) { if (stale) { console.error("run: node build.mjs"); process.exit(1); } console.log("dist/ is up to date"); }
